---
- name: Check if Neovim is already installed
  command: nvim --version
  register: neovim_installed
  ignore_errors: yes
  changed_when: false

- name: Update APT package list
  apt:
    update_cache: yes
  when: neovim_installed.rc != 0

- name: Install Neovim using APT
  apt:
    name: neovim
    state: present
  when: neovim_installed.rc != 0

