---
- name: Check if Neovim is already installed
  command: nvim --version
  register: neovim_installed
  ignore_errors: yes
  changed_when: false

- name: Detect system architecture
  command: uname -m
  register: system_architecture
  changed_when: false
  when: neovim_installed.rc != 0

- name: Set architecture-specific Neovim tarball
  set_fact:
    neovim_arch: >-
      {%- if system_architecture.stdout == "x86_64" -%}
        linux64
      {%- elif system_architecture.stdout == "aarch64" -%}
        linux-arm64
      {%- else -%}
        unsupported
      {%- endif -%}
  when: neovim_installed.rc != 0

- name: Update YUM package manager
  yum:
    name: '*'
    state: latest
  when: neovim_installed.rc != 0

- name: Install Development Tools
  yum:
    name: "@Development tools"
    state: present
  when: neovim_installed.rc != 0

- name: Install dependencies for Neovim
  yum:
    name:
      - tar
      - gcc
      - gcc-c++
      - make
      - glibc-devel
      - glibc-headers
      - libstdc++-devel
      - wget
      - tar
      - bzip2
      - gzip
      - xz
    state: present
  when: neovim_installed.rc != 0

- name: Download Neovim tarball
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v{{ neovim_version_aws_linux }}/nvim-{{ neovim_arch }}.tar.gz"
    dest: "/tmp/nvim-{{ neovim_arch }}.tar.gz"
  when: neovim_installed.rc != 0

- name: Verify downloaded Neovim tarball
  command: ls -lh /tmp/nvim-{{ neovim_arch }}.tar.gz
  register: tarball_check
  changed_when: false
  when: neovim_installed.rc != 0

- name: Extract Neovim tarball
  unarchive:
    src: "/tmp/nvim-{{ neovim_arch }}.tar.gz"
    dest: "/usr/local"
    remote_src: yes
  when: neovim_installed.rc != 0

- name: Create symlink for Neovim
  file:
    src: "/usr/local/nvim-{{ neovim_arch }}/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link
  when: neovim_installed.rc != 0

