---
- name: Ensure curl is installed (Debian)
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Install rustup (Rust installer) on Debian
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    executable: /bin/bash
  environment:
    CARGO_HOME: "{{ ansible_env.HOME }}/.cargo"
    RUSTUP_HOME: "{{ ansible_env.HOME }}/.rustup"
  become: false
  become_user: "{{ target_user }}"
