---
- name: Include OS-specific task file
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Show where pyenv was cloned
  debug:
    msg: "pyenv was cloned to: /home/myuser/.pyenv"

- name: Clone pyenv
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: "/home/{{ target_user.stdout }}/.pyenv"
    update: no
  become: true
  become_user: "{{ target_user.stdout }}"

- name: Fix ownership of pyenv directory
  file:
    path: "/home/{{ target_user.stdout }}/.pyenv"
    state: directory
    recurse: yes
    owner: "{{ target_user.stdout }}"
    group: "{{ target_user.stdout }}"
    mode: '0755'

- name: Install Python {{ python_version }} with pyenv
  shell: |
    export PYENV_ROOT="/home/{{ target_user.stdout }}/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    pyenv install -s {{ python_version }}
    pyenv global {{ python_version }}
  args:
    executable: /bin/bash
  environment:
    PYENV_ROOT: "/home/{{ target_user.stdout }}/.pyenv"
  become: true
  become_user: "{{ target_user.stdout }}"

- name: Create venv for Poetry
  shell: |
    /home/{{ target_user.stdout }}/.pyenv/versions/{{ python_version }}/bin/python -m venv /home/{{ target_user.stdout }}/.venvs/poetry
    /home/{{ target_user.stdout }}/.venvs/poetry/bin/pip install -U pip setuptools
    /home/{{ target_user.stdout }}/.venvs/poetry/bin/pip install poetry
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ target_user.stdout }}"

- name: Install uv using pip from pyenv
  shell: |
    /home/{{ target_user.stdout }}/.pyenv/versions/{{ python_version }}/bin/python -m venv /home/{{ target_user.stdout }}/.venvs/uv
    /home/{{ target_user.stdout }}/.venvs/uv/bin/pip install -U pip setuptools
    /home/{{ target_user.stdout }}/.venvs/uv/bin/pip install uv
  become: true
  become_user: "{{ target_user.stdout }}"

- name: Fix ownership of pyenv directory
  file:
    path: "/home/{{ target_user.stdout }}/.pyenv"
    state: directory
    recurse: yes
    owner: "{{ target_user.stdout }}"
    group: "{{ target_user.stdout }}"
    mode: '0755'

