---
- name: Install system dependencies for pyenv (Amazon Linux / RedHat)
  dnf:
    name:
      - make
      - gcc
      - gcc-c++
      - kernel-devel
      - openssl-devel
      - bzip2-devel
      - libffi-devel
      - zlib-devel
      - readline-devel
      - sqlite-devel
      - wget
      - curl
      - llvm
      - ncurses-devel
    state: present
    update_cache: yes

