---
- name: Install Docker, Git, and Redshift CLI (RG)
  hosts: localhost
  become: yes
  roles:
    - role: setup
      tags: setup
    - role: deps
      tags: deps
    - role: node
      tags: node
    - role: rust
      tags: rust
    - role: tools
      tags: tools
    - role: docker
      tags: docker
    - role: fish
      tags: fish
    - role: python
      tags: python
    - role: go
      tags: go
    - role: neovim
      tags: neovim
    - role: terraform
      tags: terraform
    - role: k8s
      tags: k8s


    # Erlang installation failing, need to fix
    # - erlang
